theme: jekyll-theme-minimal
title: Peak Locator
description: Deterministic Peak Detection for Multi-Dimensional Data
logo: docs/assets/peak_detection_diagram.png

# Configure GitHub Pages to serve from docs folder
docs_source: docs
